# Generated by Django 4.1.2 on 2022-10-17 12:58

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='is_published',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='question',
            name='pub_date',
            field=models.DateTimeField(default=datetime.datetime(2022, 10, 17, 12, 58, 34, 953108, tzinfo=datetime.timezone.utc), verbose_name='date published'),
        ),
    ]
