# Generated by Django 4.1.2 on 2022-10-19 19:05

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0002_question_is_published_alter_question_pub_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='votes',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='question',
            name='pub_date',
            field=models.DateTimeField(default=datetime.datetime(2022, 10, 19, 19, 5, 12, 614869, tzinfo=datetime.timezone.utc), verbose_name='date published'),
        ),
        migrations.RunSQL(
            '''
            UPDATE 
                polls_question AS q 
            SET
                votes = c.votes
            FROM 
                (SELECT 
                    question_id,
                    SUM(vote) AS votes
                FROM
                    polls_choice
                GROUP BY
                    question_id) AS c 
            WHERE 
                q.id = c.question_id;
            '''
        ),
    ]
