# Generated by Django 4.1.2 on 2022-11-11 03:30

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0004_remove_question_is_published_question_end_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='pub_date',
            field=models.DateTimeField(default=datetime.datetime(2022, 11, 11, 3, 30, 54, 849412, tzinfo=datetime.timezone.utc), verbose_name='date published'),
        ),
        migrations.AddIndex(
            model_name='question',
            index=models.Index(fields=['end_date'], name='polls_quest_end_dat_935f39_idx'),
        ),
    ]
